# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.markdown_extension:
        class: AppBundle\Twig\MarkdownExtension
        tags:
              - { name: twig.extension }
        #arguments: ['@app.markdown_transformer']
        autowire: true
    app.markdown_transformer:
        class: AppBundle\Service\MarkdownTransformer
        arguments: ['@markdown.parser','@doctrine_cache.providers.my_markdown_cache']
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
